config/routes.rb
DummyTestingCfdi::Application.routes.draw do

  resources :electronic_invoices

  root 'electronic_invoices#index'

  

end

app/models/electronic_invoice.rb
class ElectronicInvoice < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :certificate_url, SatDucumentUploader

  attr_accessor :encryption_key

  def save_certificate certificate_path
    service = connect_with_service
    service.upload_certificate certificate_path
    certificate_url
  end

  def save_key key_path
    service = connect_with_service
    convert_key_to_pem key_path
    service.upload_key "tmp/#{@uer.rfc}.key.pem"
    key_url
  end

  def get_encryption_key
    self.encryption_key || generate_encryption_key
  end

  def generate_encryption_key
    self.update_attributes(encryption_key: OpenSSL::Cipher.new("AES-256-ECB").random_key)
    self.encryption_key
  end

  private

  def connect_with_service
    UserCredentialService.new self
  end

  def convert_key_to_pem key_path
    puts 'Convert to pem'
    %x{ openssl pkcs8 -inform DER -in #{key_path} -passin pass:somePassword -out tmp/#{@user.rfc}.key.pem }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/electronic_invoices_controller.rb
class ElectronicInvoicesController < ApplicationController
  before_action :set_electronic_invoice, only: :show

  def index
    @electronic_invoices = ElectronicInvoice.all
  end

  def show
  end

  def new
    @user = User.where(rfc: 'TUMG620310R95').first
    #@user_certificate = @user.certificate_url
    @electronic_invoice = ElectronicInvoice.new
  end

  def create
    @user = User.where(rfc: 'TUMG620310R95').first
    @electronic_invoice = ElectronicInvoice.new(request: electronic_invoice_params(params).to_s)
    @electronic_invoice.xml_response = request_to_stamp params

    respond_to do |format|
      if @electronic_invoice.save
        format.html { redirect_to @electronic_invoice, notice: 'Successfully' }
        format.json { render action: 'show', status: :created, location: @electronic_invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @electronic_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def electronic_invoice_params params
    {
      user_keys: {
        id:                   Rails.application.config.fm_id,
        password:             Rails.application.config.fm_password,
        namespace:            Rails.application.config.fm_namespace,
        endpoint:             Rails.application.config.fm_endpoint,
        wsdl:                 Rails.application.config.fm_wsdl,
        log:                  Rails.application.config.fm_log,
        ssl_verify_mode:      Rails.application.config.fm_ssl_verify_mode
      },
      pac_provider:           'FacturacionModerna',
      biller: {
         certificate:         File.open('./spec/fixtures/example_certificates/TUMG620310R95/TUMG620310R95_1210241209S.cer'), #@user_credentials.get_certificate,
         key:                 File.open('spec/fixtures/example_certificates/TUMG620310R95/TUMG620310R95_1210241209S.key.pem'),#@user_credentials.get_key,
         password:            '12345678a'
      },
      bill: {
        factura: {
          folio:              '101',
          serie:              'A',
          fecha:              Time.now,
          formaDePago:        'Pago en una sola exhibicion',
          condicionesDePago:  'Contado',
          metodoDePago:       'Efectivo',
          lugarExpedicion:    'San Pedro Garza Garcia, Nuevo Leon, Mexico',
          NumCtaPago:         '',
          moneda:             'MNX'
        },
        conceptos: [
          { cantidad:         3,
            unidad:           'PIEZA',
            descripcion:      'CAJA DE HOJAS BLANCAS TAMANO CARTA',
            valorUnitario:    450.00,
            importe:          1350.00
          },
          { cantidad:         8,
            unidad:           'PIEZA',
            descripcion:      'RECOPILADOR PASTA DURA 3 ARILLOS',
            valorUnitario:    18.50,
            importe:          148.00
          },
        ],
        emisor: {
          rfc:                @user.rfc,
          nombre:             @user.name,
          domicilioFiscal: {
            calle:            'RIO GUADALQUIVIR',
            noExterior:       '238',
            noInterior:       '314',
            colonia:          'ORIENTE DEL VALLE',
            localidad:        'No se que sea esto, pero va',
            referencia:       'Sin Referencia',
            municipio:        'San Pedro Garza Garcia',
            estado:           'Nuevo Leon',
            pais:             'Mexico',
            codigoPostal:     '66220'
          },
          expedidoEn: {
            calle:            'RIO GUADALQUIVIR',
            noExterior:       '238',
            noInterior:       '314',
            colonia:          'ORIENTE DEL VALLE',
            localidad:        'Monterrey',
            referencia:       'Sin Referencia',
            municipio:        'San Pedro Garza Garcia',
            estado:           'Nuevo Leon',
            pais:             'Mexico',
            codigoPostal:     '66220'
          },
          regimenFiscal:      'REGIMEN GENERAL DE LEY PERSONAS MORALES'
        },
        emisor_pass:          @user.pass_sat,
        cliente: {
          rfc:                'XAXX010101000',
          nombre:             'PUBLICO EN GENERAL',
          domicilioFiscal: {
            calle:            'CERRADA DE AZUCENAS',
            noExterior:       '109',
            colonia:          'REFORMA',
            municipio:        'Oaxaca de Juarez',
            estado:           'Oaxaca',
            pais:             'Mexico',
            codigoPostal:     '68050'
          }
        },
        impuestos: {
          impuesto:           'IVA'
        }
      }
    }
  end

  def set_electronic_invoice
    @electronic_invoice = ElectronicInvoice.find params[:id]
  end

  def request_to_stamp params
    cfdi_response = FacturacionElectronica.create_cfdi electronic_invoice_params params
    puts '='*100
    puts cfdi_response
    cfdi_response[:xml]
  end

end

app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
  def edit
  end

  def update
    @user = User.find params[:id]
    @user.certificate_url = params[:file]
    @user.save!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/electronic_invoices_helper.rb
module ElectronicInvoicesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/electronic_invoices/_form.html.erb
<%= form_for(@electronic_invoice) do |f| %>
  <div class='field'>
    <%= f.label :folio %>
    <%= f.text_field :folio, value: ['101', '102', '103', '104'].sample %>
  </div>
  <div class='field'>
    <%= f.label :serie %>
    <%= f.text_field :serie, value: ['AA', 'BB', 'CC', 'DD'].sample %>
  </div>
  <div class='field'>
    <%= f.label :fecha %>
    <%= f.date_field :fecha %>
  </div>
  <div class='field'>
    <%= f.label :forma_pago %>
    <%= f.text_field :forma_pago, value: 'Pago en una sola exhibicion' %>
  </div>
  <div class='field'>
    <%= f.label :condiciones_pago %>
    <%= f.text_field :condiciones_pago, value: 'Contado' %>
  </div>
  <div class='field'>
    <%= f.label :metodo_pago %>
    <%= f.text_field :metodo_pago, value: ['Cheque', 'Efectivo'].sample %>
  </div>
  <div class='field'>
    <%= f.label :expedido %>
    <%= f.text_field :expedido, value: 'San Pedro Garza Garcia, Nuevo Leon, Mexico' %>
  </div>
  <div class='field'>
    <%= f.label :numero_cuenta_pago %>
    <%= f.text_field :numero_cuenta_pago %>
  </div>
  <div class='field'>
    <%= f.label :moneda %>
    <%= f.text_field :moneda, value: 'MXN' %>
  </div>

  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/electronic_invoices/index.html.erb
<h1>Electroinc Invoices</h1>
<div>
  <%= link_to 'New Invoice', new_electronic_invoice_path %>
</div>
<table>
  <thead>
    <th>Number</th>
    <th>Request</th>
  </thead>
  <tbody>
    <%- @electronic_invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.id %></td>
        <td><%= invoice.request %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/electronic_invoices/new.html.erb
<h1>Request for a new electroinc invoice</h1>

<%= render 'form' %>

app/views/electronic_invoices/show.html.erb
<p id='notice'><%= notice %>

<p>
  <strong>Request</strong>
  <%= @electronic_invoice.request %>
</p>

<p>
  <strong>XML response</strong>
  <%= @electronic_invoice.xml_response %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DummyTestingCfdi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>